### ISSUE TITLE
too many request

### ISSUE THREAD

**Issue by aiser86** [tinohager/Nager.AmazonProductAdvertising#108]
Hi guys,
The new version (2.0.6) retrive too many request a lot of time. I rolback to the old version 1.2.x because still working. I do not have any ideea that it's my fault or problem on dll.
Anyone have the same problem?

**Comment by tinohager** [comment]
Which request is fired to often?

**Comment by aiser86** [comment]
SearchItemsAsync
and
GetItemsAsync

endpoint is IT

Thanks

Il giorno mar 5 nov 2019 alle ore 16:52 Tino Hager <notifications@github.com>
ha scritto:

**Comment by WagnerW** [comment]
I'm giving up the API to either V. 4 or V.5 it's answering "TooManyRequest" even blocking all Robots (because it counts as access) unfortunately Amazon wants you to sell a lot with few hits, as I sell little they limit you access .

**Comment by aiser86** [comment]
The problem is on ApI 5.0 because with the old version i do not recognize
the problem.

They change some policy between v4 and v5?

Il giorno mer 6 nov 2019 alle ore 12:47 WagnerW <notifications@github.com>
ha scritto:

**Comment by WagnerW** [comment]
I was also using V.4 without problems, and V.5 was being tested and I realized it was very sensitive to error, but for me V.4 also started to return the "TooManyRequest" answer on the AWS forums. complaining about V.5, I don't know what I do anymore.

[https://forums.aws.amazon.com/thread.jspa?threadID=311773&tstart=0](url)

**Comment by tinohager** [comment]
You can cache your requests for 24h. This is an optimization for TooManyRequest

(h) You will not store or cache Product Advertising Content consisting of an image, but you may store a link to Product Advertising Content consisting of an image for up to 24 hours. You may store other Product Advertising Content that does not consist of images for caching purposes for up to 24 hours, but if you do so you must immediately thereafter refresh and re-display the Product Advertising Content by making a call to PA API or retrieving a new Data Feed and refreshing the Product Advertising Content on your application immediately thereafter. Unless otherwise notified by us, you may store individual Amazon Standard Identification Numbers (ASINs) for an indefinite period until the termination of this License. Notwithstanding the foregoing, if your application includes a client application, the client application may not store or cache Product Advertising Content. Upon our request you will, within three business days of our request, furnish us with a copy of any client application that includes or uses Product Advertising Content for the purpose of verifying your compliance with this License.

https://affiliate-program.amazon.com/help/operating/policies/#Associates%20Program%20IP%20License

**Comment by aiser86** [comment]
This happen if we do not cache the result and call the same ASIN?
Or is just a suggestion to optimize our code?

Il giorno mer 6 nov 2019 alle ore 16:00 Tino Hager <notifications@github.com>
ha scritto:

**Comment by tinohager** [comment]
It is a suggestion to use the available requests useful

**Comment by WagnerW** [comment]
Sorry Tino, I do not understand if you know how to optimize our code pass this tip, because in my case I already make use of cache in the controllers and use CloudFlare and it is not working.
